from __future__ import annotations

from models.formation import FormationShape, FormationSlot
from models.position import Position


def _slots_433() -> tuple[FormationSlot, ...]:
    return (
        FormationSlot(
            slot_id="GK",
            base_zone="defensive_third",
            line="goalkeeper",
            lateral_band="center",
            vertical_band="deep",
            preferred_positions=(Position.GK,),
            adjacency_slots=("RCB", "LCB"),
            support_links=("RCB", "LCB", "DM"),
            attacking_lane_access=("central_build",),
            defensive_responsibility=("box",),
        ),
        FormationSlot(
            slot_id="RB",
            base_zone="defensive_third",
            line="defense",
            lateral_band="right_wide",
            vertical_band="deep",
            preferred_positions=(Position.RB,),
            adjacency_slots=("RCB", "RCM", "RW"),
            support_links=("RCM", "RW"),
            attacking_lane_access=("right_flank", "right_halfspace"),
            defensive_responsibility=("right_flank",),
        ),
        FormationSlot(
            slot_id="RCB",
            base_zone="defensive_third",
            line="defense",
            lateral_band="right_halfspace",
            vertical_band="deep",
            preferred_positions=(Position.CB,),
            adjacency_slots=("GK", "RB", "LCB", "DM"),
            support_links=("RB", "DM"),
            attacking_lane_access=("central_build",),
            defensive_responsibility=("box", "right_halfspace"),
        ),
        FormationSlot(
            slot_id="LCB",
            base_zone="defensive_third",
            line="defense",
            lateral_band="left_halfspace",
            vertical_band="deep",
            preferred_positions=(Position.CB,),
            adjacency_slots=("GK", "LB", "RCB", "DM"),
            support_links=("LB", "DM"),
            attacking_lane_access=("central_build",),
            defensive_responsibility=("box", "left_halfspace"),
        ),
        FormationSlot(
            slot_id="LB",
            base_zone="defensive_third",
            line="defense",
            lateral_band="left_wide",
            vertical_band="deep",
            preferred_positions=(Position.LB,),
            adjacency_slots=("LCB", "LCM", "LW"),
            support_links=("LCM", "LW"),
            attacking_lane_access=("left_flank", "left_halfspace"),
            defensive_responsibility=("left_flank",),
        ),
        FormationSlot(
            slot_id="DM",
            base_zone="middle_third",
            line="midfield",
            lateral_band="center",
            vertical_band="middle",
            preferred_positions=(Position.DM, Position.CM),
            adjacency_slots=("RCB", "LCB", "RCM", "LCM", "ST"),
            support_links=("RCM", "LCM", "ST"),
            attacking_lane_access=("central_build", "halfspaces"),
            defensive_responsibility=("zone14", "counter_rest"),
        ),
        FormationSlot(
            slot_id="RCM",
            base_zone="middle_third",
            line="midfield",
            lateral_band="right_halfspace",
            vertical_band="middle",
            preferred_positions=(Position.CM, Position.DM),
            adjacency_slots=("RB", "DM", "ST", "RW"),
            support_links=("RB", "RW", "ST"),
            attacking_lane_access=("right_halfspace",),
            defensive_responsibility=("right_halfspace",),
        ),
        FormationSlot(
            slot_id="LCM",
            base_zone="middle_third",
            line="midfield",
            lateral_band="left_halfspace",
            vertical_band="middle",
            preferred_positions=(Position.CM, Position.DM),
            adjacency_slots=("LB", "DM", "ST", "LW"),
            support_links=("LB", "LW", "ST"),
            attacking_lane_access=("left_halfspace",),
            defensive_responsibility=("left_halfspace",),
        ),
        FormationSlot(
            slot_id="RW",
            base_zone="final_third",
            line="attack",
            lateral_band="right_wide",
            vertical_band="high",
            preferred_positions=(Position.RW, Position.AM),
            adjacency_slots=("RB", "RCM", "ST"),
            support_links=("RB", "RCM", "ST"),
            attacking_lane_access=("right_flank", "right_halfspace"),
            defensive_responsibility=("right_press_lane",),
        ),
        FormationSlot(
            slot_id="LW",
            base_zone="final_third",
            line="attack",
            lateral_band="left_wide",
            vertical_band="high",
            preferred_positions=(Position.LW, Position.AM),
            adjacency_slots=("LB", "LCM", "ST"),
            support_links=("LB", "LCM", "ST"),
            attacking_lane_access=("left_flank", "left_halfspace"),
            defensive_responsibility=("left_press_lane",),
        ),
        FormationSlot(
            slot_id="ST",
            base_zone="final_third",
            line="attack",
            lateral_band="center",
            vertical_band="high",
            preferred_positions=(Position.ST,),
            adjacency_slots=("RW", "LW", "RCM", "LCM", "DM"),
            support_links=("RW", "LW", "RCM", "LCM"),
            attacking_lane_access=("box", "central_channel"),
            defensive_responsibility=("first_press",),
        ),
    )


def _slots_4231() -> tuple[FormationSlot, ...]:
    slots = list(_slots_433())
    slots = [s for s in slots if s.slot_id not in {"DM", "RCM", "LCM", "ST"}]
    slots.extend(
        [
            FormationSlot(
                slot_id="RDM",
                base_zone="middle_third",
                line="midfield",
                lateral_band="right_halfspace",
                vertical_band="middle",
                preferred_positions=(Position.DM, Position.CM),
                adjacency_slots=("RCB", "RB", "LDM", "AM"),
                support_links=("RB", "AM", "RW"),
                attacking_lane_access=("right_halfspace",),
                defensive_responsibility=("counter_rest", "zone14"),
            ),
            FormationSlot(
                slot_id="LDM",
                base_zone="middle_third",
                line="midfield",
                lateral_band="left_halfspace",
                vertical_band="middle",
                preferred_positions=(Position.DM, Position.CM),
                adjacency_slots=("LCB", "LB", "RDM", "AM"),
                support_links=("LB", "AM", "LW"),
                attacking_lane_access=("left_halfspace",),
                defensive_responsibility=("counter_rest", "zone14"),
            ),
            FormationSlot(
                slot_id="AM",
                base_zone="middle_third",
                line="attack_mid",
                lateral_band="center",
                vertical_band="high",
                preferred_positions=(Position.AM, Position.CM),
                adjacency_slots=("RDM", "LDM", "RW", "LW", "ST"),
                support_links=("RW", "LW", "ST"),
                attacking_lane_access=("halfspaces", "central_channel"),
                defensive_responsibility=("press_shadow",),
            ),
            FormationSlot(
                slot_id="ST",
                base_zone="final_third",
                line="attack",
                lateral_band="center",
                vertical_band="high",
                preferred_positions=(Position.ST,),
                adjacency_slots=("RW", "LW", "AM"),
                support_links=("RW", "LW", "AM"),
                attacking_lane_access=("box", "central_channel"),
                defensive_responsibility=("first_press",),
            ),
        ]
    )
    return tuple(slots)


def _slots_352() -> tuple[FormationSlot, ...]:
    return (
        FormationSlot(
            "GK",
            "defensive_third",
            "goalkeeper",
            "center",
            "deep",
            (Position.GK,),
            ("RCB", "CB", "LCB"),
            ("RCB", "CB", "LCB"),
            ("central_build",),
            ("box",),
        ),
        FormationSlot(
            "RCB",
            "defensive_third",
            "defense",
            "right_halfspace",
            "deep",
            (Position.CB,),
            ("GK", "CB", "RWB", "RCM"),
            ("RWB", "RCM"),
            ("central_build",),
            ("box", "right_halfspace"),
        ),
        FormationSlot(
            "CB",
            "defensive_third",
            "defense",
            "center",
            "deep",
            (Position.CB,),
            ("GK", "RCB", "LCB", "DM"),
            ("DM",),
            ("central_build",),
            ("box", "zone14"),
        ),
        FormationSlot(
            "LCB",
            "defensive_third",
            "defense",
            "left_halfspace",
            "deep",
            (Position.CB,),
            ("GK", "CB", "LWB", "LCM"),
            ("LWB", "LCM"),
            ("central_build",),
            ("box", "left_halfspace"),
        ),
        FormationSlot(
            "RWB",
            "middle_third",
            "wingback",
            "right_wide",
            "middle",
            (Position.RB, Position.RW),
            ("RCB", "RCM", "RST"),
            ("RCM", "RST"),
            ("right_flank",),
            ("right_flank", "right_press_lane"),
        ),
        FormationSlot(
            "LWB",
            "middle_third",
            "wingback",
            "left_wide",
            "middle",
            (Position.LB, Position.LW),
            ("LCB", "LCM", "LST"),
            ("LCM", "LST"),
            ("left_flank",),
            ("left_flank", "left_press_lane"),
        ),
        FormationSlot(
            "DM",
            "middle_third",
            "midfield",
            "center",
            "middle",
            (Position.DM, Position.CM),
            ("CB", "RCM", "LCM"),
            ("RCM", "LCM"),
            ("central_build",),
            ("counter_rest", "zone14"),
        ),
        FormationSlot(
            "RCM",
            "middle_third",
            "midfield",
            "right_halfspace",
            "middle",
            (Position.CM, Position.DM),
            ("RWB", "DM", "RST"),
            ("RWB", "RST"),
            ("right_halfspace",),
            ("right_halfspace",),
        ),
        FormationSlot(
            "LCM",
            "middle_third",
            "midfield",
            "left_halfspace",
            "middle",
            (Position.CM, Position.DM),
            ("LWB", "DM", "LST"),
            ("LWB", "LST"),
            ("left_halfspace",),
            ("left_halfspace",),
        ),
        FormationSlot(
            "RST",
            "final_third",
            "attack",
            "right_halfspace",
            "high",
            (Position.ST,),
            ("RWB", "RCM", "LST"),
            ("RWB", "RCM", "LST"),
            ("box", "right_halfspace"),
            ("first_press",),
        ),
        FormationSlot(
            "LST",
            "final_third",
            "attack",
            "left_halfspace",
            "high",
            (Position.ST,),
            ("LWB", "LCM", "RST"),
            ("LWB", "LCM", "RST"),
            ("box", "left_halfspace"),
            ("first_press",),
        ),
    )


class FormationFactory:
    """Factory for canonical formation shapes."""

    @staticmethod
    def by_code(code: str) -> FormationShape:
        normalized = code.strip()
        if normalized == "4-3-3":
            return FormationShape(
                code="4-3-3",
                slot_definitions=_slots_433(),
                structural_tags={
                    "natural_width": 0.78,
                    "central_compactness": 0.62,
                    "rest_defense_shape": 0.58,
                    "press_front_line": 0.70,
                },
            )
        if normalized == "4-2-3-1":
            return FormationShape(
                code="4-2-3-1",
                slot_definitions=_slots_4231(),
                structural_tags={
                    "natural_width": 0.72,
                    "central_compactness": 0.68,
                    "rest_defense_shape": 0.74,
                    "press_front_line": 0.66,
                },
            )
        if normalized == "3-5-2":
            return FormationShape(
                code="3-5-2",
                slot_definitions=_slots_352(),
                structural_tags={
                    "natural_width": 0.80,
                    "central_compactness": 0.76,
                    "rest_defense_shape": 0.81,
                    "press_front_line": 0.64,
                },
            )

        # Fallback to a broadly balanced 4-3-3 shape to keep runtime robust.
        return FormationFactory.by_code("4-3-3")
