from __future__ import annotations

from models.position import Position
from models.role import Role
from models.duty import Duty


ROLE_SUPPORTED_POSITIONS: dict[Role, set[Position]] = {
    Role.SHOT_STOPPER: {Position.GK},
    Role.SWEEPER_KEEPER: {Position.GK},
    Role.FULL_BACK: {Position.RB, Position.LB},
    Role.WING_BACK: {Position.RB, Position.LB},
    Role.INVERTED_FULL_BACK: {Position.RB, Position.LB},
    Role.DEFENSIVE_FULL_BACK: {Position.RB, Position.LB},
    Role.CENTRAL_DEFENDER: {Position.CB},
    Role.STOPPER: {Position.CB},
    Role.BALL_PLAYING_DEFENDER: {Position.CB},
    Role.WIDE_BACK: {Position.CB},
    Role.ANCHOR: {Position.DM},
    Role.BALL_WINNING_MIDFIELDER: {Position.DM, Position.CM},
    Role.REGISTA: {Position.DM, Position.CM},
    Role.HALF_BACK: {Position.DM},
    Role.BOX_TO_BOX_MIDFIELDER: {Position.CM},
    Role.MEZZALA: {Position.CM},
    Role.CARRILERO: {Position.CM},
    Role.BOX_CRASHER: {Position.CM},
    Role.SHADOW_STRIKER: {Position.AM},
    Role.TREQUARTISTA: {Position.AM},
    Role.ENGANCHE: {Position.AM},
    Role.HALF_WINGER: {Position.AM},
    Role.WINGER: {Position.RW, Position.LW},
    Role.INVERTED_WINGER: {Position.RW, Position.LW},
    Role.WIDE_PLAYMAKER: {Position.RW, Position.LW},
    Role.DEFENSIVE_WINGER: {Position.RW, Position.LW},
    Role.TARGET_MAN: {Position.ST},
    Role.POACHER: {Position.ST},
    Role.SECONDARY_STRIKER: {Position.ST, Position.AM},
    Role.ADVANCED_FORWARD: {Position.ST},
    Role.FALSE_NINE: {Position.ST},
}

ROLE_SUPPORTED_DUTIES: dict[Role, set[Duty]] = {
    Role.SHOT_STOPPER: {Duty.DEFEND, Duty.SUPPORT},
    Role.SWEEPER_KEEPER: {Duty.SUPPORT, Duty.ATTACK},
    Role.FULL_BACK: {Duty.DEFEND, Duty.SUPPORT, Duty.ATTACK},
    Role.WING_BACK: {Duty.SUPPORT, Duty.ATTACK},
    Role.INVERTED_FULL_BACK: {Duty.DEFEND, Duty.SUPPORT},
    Role.DEFENSIVE_FULL_BACK: {Duty.DEFEND, Duty.BALANCED},
    Role.CENTRAL_DEFENDER: {Duty.DEFEND, Duty.SUPPORT},
    Role.STOPPER: {Duty.DEFEND, Duty.SUPPORT},
    Role.BALL_PLAYING_DEFENDER: {Duty.DEFEND, Duty.SUPPORT},
    Role.WIDE_BACK: {Duty.DEFEND, Duty.SUPPORT},
    Role.ANCHOR: {Duty.DEFEND, Duty.BALANCED},
    Role.BALL_WINNING_MIDFIELDER: {Duty.DEFEND, Duty.SUPPORT},
    Role.REGISTA: {Duty.DEFEND, Duty.SUPPORT},
    Role.HALF_BACK: {Duty.DEFEND, Duty.BALANCED},
    Role.BOX_TO_BOX_MIDFIELDER: {Duty.SUPPORT, Duty.ATTACK},
    Role.MEZZALA: {Duty.SUPPORT, Duty.ATTACK},
    Role.CARRILERO: {Duty.SUPPORT, Duty.BALANCED},
    Role.BOX_CRASHER: {Duty.ATTACK, Duty.BALANCED},
    Role.SHADOW_STRIKER: {Duty.ATTACK, Duty.BALANCED},
    Role.TREQUARTISTA: {
        Duty.SUPPORT,
        Duty.ATTACK,
    },
    Role.ENGANCHE: {Duty.SUPPORT, Duty.BALANCED},
    Role.HALF_WINGER: {Duty.SUPPORT, Duty.ATTACK},
    Role.WINGER: {Duty.SUPPORT, Duty.ATTACK},
    Role.INVERTED_WINGER: {Duty.SUPPORT, Duty.ATTACK},
    Role.WIDE_PLAYMAKER: {Duty.SUPPORT, Duty.ATTACK},
    Role.DEFENSIVE_WINGER: {Duty.DEFEND, Duty.SUPPORT},
    Role.TARGET_MAN: {Duty.SUPPORT, Duty.ATTACK},
    Role.POACHER: {Duty.ATTACK, Duty.BALANCED},
    Role.SECONDARY_STRIKER: {Duty.SUPPORT, Duty.ATTACK},
    Role.ADVANCED_FORWARD: {Duty.ATTACK, Duty.BALANCED},
    Role.FALSE_NINE: {Duty.SUPPORT, Duty.ATTACK},
}
